# Generated by Django 5.2.10 on 2026-01-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('course', models.CharField(max_length=100, verbose_name='Курс/Направление')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Фотография')),
                ('data_processing_consent', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название достижения')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('achievement_type', models.CharField(choices=[('project', 'Учебный проект'), ('competition', 'Олимпиада/Конкурс'), ('practice', 'Практика/Стажировка'), ('certificate', 'Сертификат'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип достижения')),
                ('document', models.FileField(blank=True, null=True, upload_to='achievements/documents/', verbose_name='Документ (грамота, сертификат)')),
                ('project_file', models.FileField(blank=True, null=True, upload_to='achievements/projects/', verbose_name='Файл проекта')),
                ('date_achieved', models.DateField(verbose_name='Дата получения')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено для публикации')),
                ('is_public', models.BooleanField(default=False, verbose_name='Показывать на доске почета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='portfolio.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-date_achieved'],
            },
        ),
    ]
