# Generated by Django 5.2.8 on 2026-02-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_skill_student_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hide_contacts',
            field=models.BooleanField(default=False, verbose_name='Скрыть контакты'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Сделать профиль приватным'),
        ),
    ]
