# Generated by Django 5.2.8 on 2026-03-31 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_student_hide_contacts_student_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Профиль одобрен администратором'),
        ),
        migrations.AddField(
            model_name='student',
            name='social_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на соцсеть'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_card_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер студенческого билета'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100, verbose_name='Группа / Специальность'),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('sector', models.CharField(choices=[('it', 'IT'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('other', 'Другое')], max_length=50, verbose_name='Сфера деятельности')),
                ('website', models.URLField(blank=True, verbose_name='Сайт компании')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('registration_purpose', models.TextField(blank=True, verbose_name='Цель регистрации')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Аккаунт одобрен администратором')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Работодатель',
                'verbose_name_plural': 'Работодатели',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Обработано')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='portfolio.student', verbose_name='Студент')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='portfolio.employer', verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Запрос контактов',
                'verbose_name_plural': 'Запросы контактов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/', verbose_name='Файл приказа (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Поставил статус')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_orders', to='portfolio.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Приказ зачисления',
                'verbose_name_plural': 'Приказы зачисления',
                'ordering': ['-created_at'],
            },
        ),
    ]
