# Generated by Django 5.2.8 on 2026-03-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_student_is_approved_student_social_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='student',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа администратора'),
        ),
    ]
