# Generated by Django 5.2.8 on 2026-04-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_student_birth_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollmentOrder',
        ),
    ]
