# Generated by Django 5.2.8 on 2026-04-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_delete_enrollmentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
    ]
