# Generated by Django 5.2.8 on 2026-04-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_managerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_submitted_for_review',
            field=models.BooleanField(default=False, verbose_name='Отправлен на модерацию'),
        ),
    ]
