# Generated by Django 5.2.8 on 2026-05-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_student_is_submitted_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_incognito',
            field=models.BooleanField(default=False, verbose_name='Режим инкогнито (скрыть личность)'),
        ),
    ]
