# Generated by Django 5.2.8 on 2026-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_student_is_incognito'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на проект/документ (GitHub, PDF, сайт)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание (необязательно)'),
        ),
    ]
