# Generated by Django 5.2.8 on 2026-05-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_achievement_link_url_alter_achievement_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='document',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='project_file',
        ),
        migrations.AddField(
            model_name='achievement',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ссылка (GitHub / PDF / сайт проекта)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date_achieved',
            field=models.DateField(blank=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (необязательно)'),
        ),
    ]
