# Generated by Django 5.2.8 on 2026-05-05 10:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Сопроводительное сообщение')),
                ('status', models.CharField(choices=[('submitted', 'Отправлен'), ('reviewing', 'На рассмотрении'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='submitted', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='Регион')),
                ('tech_stack', models.CharField(blank=True, max_length=255, verbose_name='Стек технологий')),
                ('employment_type', models.CharField(choices=[('internship', 'Стажировка'), ('part_time', 'Частичная занятость'), ('full_time', 'Полная занятость'), ('project', 'Проектная работа')], default='internship', max_length=20, verbose_name='Формат')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('closed', 'Закрыта')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичная')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='is_handled',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='employer_message',
            field=models.TextField(blank=True, verbose_name='Комментарий работодателя'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запроса'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа студента'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('pending_student', 'Ожидает решения студента'), ('approved_by_student', 'Одобрен студентом'), ('rejected_by_student', 'Отклонен студентом'), ('expired', 'Истек')], default='pending_student', max_length=30, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='student_response_message',
            field=models.TextField(blank=True, verbose_name='Ответ студента'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_contact_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предпочтительный способ связи'),
        ),
        migrations.AddField(
            model_name='student',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='student',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AddConstraint(
            model_name='contactrequest',
            constraint=models.UniqueConstraint(fields=('employer', 'student'), name='unique_contact_request_per_pair'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portfolio.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='portfolio.employer', verbose_name='Работодатель'),
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portfolio.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('vacancy', 'student'), name='unique_student_application_per_vacancy'),
        ),
    ]
