# Generated by Django 5.2.8 on 2026-05-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_application_vacancy_remove_contactrequest_is_handled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employer_message',
            field=models.TextField(blank=True, verbose_name='Сообщение работодателя'),
        ),
    ]
