# Generated by Django 5.2.8 on 2026-05-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_application_employer_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='job_search_status',
            field=models.CharField(choices=[('internship', 'Ищу стажировку'), ('job', 'В поиске работы'), ('found', 'Уже нашел работу')], default='internship', max_length=20, verbose_name='Статус поиска работы'),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение работодателя')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('response_message', models.TextField(blank=True, verbose_name='Сообщение студента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='portfolio.employer', verbose_name='Работодатель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='portfolio.student', verbose_name='Студент')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='portfolio.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Приглашение студента',
                'verbose_name_plural': 'Приглашения студентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
