# Generated by Django 5.2.8 on 2026-05-11  

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_student_job_search_status_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Контактный телефон'),
        ),
    ]
