# Generated by Django 5.2.8 on 2026-05-11 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_tech_stack_and_sector_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('specialty', models.CharField(max_length=200, verbose_name='Наименование специальности')),
                ('specialty_code', models.CharField(max_length=50, verbose_name='Код специальности')),
                ('admission_year', models.PositiveIntegerField(verbose_name='Год поступления')),
                ('graduation_year', models.PositiveIntegerField(verbose_name='Год окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='receive_vacancy_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления о новых вакансиях'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='send_notifications',
            field=models.BooleanField(default=False, verbose_name='Отправить уведомления студентам целевых групп'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='portfolio.group', verbose_name='Целевые группы (специальности)'),
        ),
    ]
