# Generated by Django 5.2.8 on 2026-06-05 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_student_consents_and_parent_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='student_response_message',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='portfolio.managerprofile', verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='manager_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа менеджера'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='manager_response_message',
            field=models.TextField(blank=True, verbose_name='Ответ менеджера'),
        ),
        migrations.AddField(
            model_name='student',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portfolio.managerprofile', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('pending_manager', 'Ожидает решения менеджера'), ('approved_by_manager', 'Одобрен менеджером'), ('rejected_by_manager', 'Отклонен менеджером'), ('expired', 'Истек')], default='pending_manager', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='target_specialties',
            field=models.TextField(blank=True, help_text='Через запятую. Уведомления получат участники с совпадающей специальностью обучения.', verbose_name='Целевые специальности'),
        ),
    ]
